spring.application.name=careerforge-api

spring.datasource.url=jdbc:postgresql://localhost:5432/careerforge
spring.datasource.username=anshika
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.port=8080

jwt.secret=123e4r5t6y7u8i9aw2dr4nju8mkit54s;
jwt.expiration=3600000

gemini.api.key=${GEMINI_API_KEY}